### ISSUE TITLE
Retrieving metadata doesnt work for me

### ISSUE THREAD

**Issue by g07kore** [mapbox/rio-tiler#2]
Import works normal, package is installed correctly, but `landsat8.metadata('LC08_L1TP_016037_20170813_20170814_01_RT', pmin=5, pmax=95)` gives me the following error.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cachetools/func.py", line 58, in wrapper
    v = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rio_tiler/landsat8.py", line 71, in metadata
    meta_data = utils.landsat_get_mtl(sceneid).get('L1_METADATA_FILE')
  File "/usr/local/lib/python2.7/dist-packages/rio_tiler/utils.py", line 217, in landsat_get_mtl
    raise Exception('Could not retrieve {} metadata'.format(sceneid))
Exception: Could not retrieve LC08_L1TP_016037_20170813_20170814_01_RT metadata

I am using Linux Ubuntu, Python 2.7.12.

**Comment by vincentsarago** [comment]
Thanks @g07kore 
I found the bug and going to fix it

I'll release a new version soon with the fix.
